### PR TITLE
Bug fix and lidar child process now works with input from lidar sensor 

### PR DESCRIPTION
**Pull request by OMara-M**
bug in lidar.py line 11, getTFminiData() should be a static method

Updated lidar_child_proc.py now works with the lidar sensor input

### CODE REVIEW

**Comment by bobby-palko** [comment]
mind removing all the python 2 example code that's commented out while you're at it?

**Comment by bobby-palko** [comment]
i'll test this tonight 👍🏻

**Comment by jon-dez** [comment]
@bobby-palko I tested this with @OMara-M on my Raspberry Pi setup. It works nice as you saw in person, but it had that one bug that is now ironed out.

**Review by jon-dez — APPROVED** [review]
Tested

**Comment by OMara-M** [comment]
> mind removing all the python 2 example code that's commented out while you're at it?

All python 2 comments removed

**Pull request merged**
